import { Inter } from 'next/font/google'
import './global.css'
import Sidebar from '../../components'

const inter = Inter({ subsets: ['latin']})

export const metadata = {
  title: 'Rose Azuma',
  description: 'Generated by Next'
}

export default function RootLayout({ children }: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className='min-h-screen bg-black'>
          <Sidebar />

          <main className='text-center text-white'>{children}</main>
        </div>
      </body>
    </html>
  )
}